import { Box, Heading, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
// import { useEffect, useState } from "react";

const Home: NextPage = () => {
  // const [data, setData] = useState("");

  // useEffect(() => {
  //   fetch("http://localhost:1337/healthcheck").then((res) =>
  //     res.json().then((d) => {
  //       setData(d);
  //     })
  //   );
  // }, []);

  return (
    <>
      <Head>
        <title>Croto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="w-screen h-screen flex flex-col justify-center items-center">
        <Heading>Welcom to Croto</Heading>
        <span className="my-4" />
        <Text>Its gonna be big!!</Text>
      </Box>
    </>
  );
};

export default Home;
